name: Continuous Integration

on:
  pull_request:
    branches: [ '*' ]
  push:
    branches: [ 'main' ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
        working-directory: server
      - name: Run tests with coverage
        run: npm run test:coverage
        working-directory: server