name: Continuous Integration

on:
  pull_request:
    branches: [ '*' ]
  push:
    branches: [ 'main' ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache server node modules
        uses: actions/cache@v3
        with:
          path: server/node_modules
          key: ${{ runner.os }}-server-node-${{ hashFiles('server/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-server-node-

      - name: Cache client node modules
        uses: actions/cache@v3
        with:
          path: client/node_modules
          key: ${{ runner.os }}-client-node-${{ hashFiles('client/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-client-node-

      - name: Install server dependencies
        run: npm install
        working-directory: server

      - name: Install client dependencies
        run: npm install
        working-directory: client

      - name: Run server tests with coverage
        run: npm run test:coverage
        working-directory: server

      - name: Run client tests
        run: npm run test
        working-directory: client